name: Build docs

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout b3d
        uses: actions/checkout@v4
        with:
          repository: "LEEF-b3d"
          path: "./LEEF-b3d"

      - name: checkout math
        uses: actions/checkout@v4
        with:
          repository: "LEEF-math"
          path: "./LEEF-math"

      - name: checkout filesystem
        uses: actions/checkout@v4
        with:
          repository: "LEEF-filesystem"
          path: "./LEEF-filesystem"

      - name: checkout class
        uses: actions/checkout@v4
        with:
          repository: "LEEF-class"
          path: "./LEEF-class"

      - name: Checkout to this repo
        uses: actions/checkout@v4

      - name: Generate docs with LDoc
        uses: lunarmodules/ldoc@v0

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: './docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4